apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: demo
  name: demo
spec:
  replicas: 5
  selector:
    matchLabels:
      run: demo
  template:
    metadata:
      labels:
        run: demo
    spec:
      containers:
      - image: index.docker.io/houami/goserver
        name: demo
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
spec:
  ports:
  - nodePort: 31001
    targetPort: 8000
    port: 8000
    protocol: TCP
  selector:
    run: demo
  type: NodePort
