apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: goserver
  name: goserver
  namespace: '${parameters.devnamespace}'
spec:
  replicas: parameters.namespace == 'dev' ? parameters.desiredReplicas = 1 : parameters.desiredReplicas = 5
  selector:
    matchLabels:
      run: goserver
  template:
    metadata:
      labels:
        run: goserver
    spec:
      containers:
        - image: index.docker.io/houami/goserver
          name: goserver
